"""add shipment indexes

Revision ID: 7be3156de95c
Revises: 952501c918aa
Create Date: 2026-03-15 13:59:38.604632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7be3156de95c'
down_revision: Union[str, Sequence[str], None] = '952501c918aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_shipment_created_at', 'shipment', ['created_at'], unique=False)
    op.create_index('idx_shipment_destination', 'shipment', ['destination'], unique=False)
    op.create_index('idx_shipment_status', 'shipment', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_shipment_status', table_name='shipment')
    op.drop_index('idx_shipment_destination', table_name='shipment')
    op.drop_index('idx_shipment_created_at', table_name='shipment')
    # ### end Alembic commands ###
