"""add updated_at column to shipment

Revision ID: 952501c918aa
Revises: 284bfdb9a63e
Create Date: 2026-03-15 13:30:01.280722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '952501c918aa'
down_revision: Union[str, Sequence[str], None] = '284bfdb9a63e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipment', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipment', 'updated_at')
    # ### end Alembic commands ###
